### ISSUE TITLE
Connecting to instagram 

### ISSUE THREAD

**Issue by MuhibRidawi** [GH05T-HUNTER5/GH05T-INSTA#132]
Connecting to instagram then it says erro

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GH05T-HUNTER5** [comment]
> Connecting to instagram then it says erro
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Share screenshot

**Comment by GH05T-HUNTER5** [comment]
We are trying to fix this issue

**Comment by MuhibRidawi** [comment]
Am I doing something wrong or it doesn't work for termux(non-root)
