### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by LEO1234567890LEO** [GH05T-HUNTER5/GH05T-INSTA#2]
[+] Started @ 2022-08-01 12:06:23.606564
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 87, in __init__
    configuration = json.load(fp)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/instagram-py", line 33, in <module>
    sys.exit(load_entry_point('instagram-py==2.0.7', 'console_scripts', 'instagram-py')())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy
    session = InstagramPySession(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 90, in __init__
    "invalid configuration file at {}".format(configuraion))
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by GH05T-HUNTER5** [comment]
> [+] Started @ 2022-08-01 12:06:23.606564 Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 87, in **init** configuration = json.load(fp) File "/data/data/com.termux/files/usr/lib/python3.10/json/**init**.py", line 293, in load return loads(fp.read(), File "/data/data/com.termux/files/usr/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/instagram-py", line 33, in sys.exit(load_entry_point('instagram-py==2.0.7', 'console_scripts', 'instagram-py')()) File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/**init**.py", line 128, in ExecuteInstagramPy session = InstagramPySession( File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 90, in **init** "invalid configuration file at {}".format(configuraion)) NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

Try Version: 3.1

**Comment by GH05T-HUNTER5** [comment]
> [+] Started @ 2022-08-01 12:06:23.606564 Traceback (most recent call last): File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 87, in **init** configuration = json.load(fp) File "/data/data/com.termux/files/usr/lib/python3.10/json/**init**.py", line 293, in load return loads(fp.read(), File "/data/data/com.termux/files/usr/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/instagram-py", line 33, in sys.exit(load_entry_point('instagram-py==2.0.7', 'console_scripts', 'instagram-py')()) File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/**init**.py", line 128, in ExecuteInstagramPy session = InstagramPySession( File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/InstagramPy/InstagramPySession.py", line 90, in **init** "invalid configuration file at {}".format(configuraion)) NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

Dude Try our new update
