### ISSUE TITLE
python install.py not working

### ISSUE THREAD

**Issue by Desaii01** [GH05T-HUNTER5/GH05T-INSTA#213]
** python install.py **
This command is not working on my mobile showing python can't open directory

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. android]
 - Browser [e.g. chrome ]
 - Version [e.g. 105.0.5195.136]

**Smartphone (please complete the following information):**
 - Device: [e.g. vivo y91i]
 - OS: [e.g. android 8.1.0]
 - Browser [e.g. chrome]
 - Version [e.g. 105.0.5195.136]

**Additional context**

**Comment by GH05T-HUNTER5** [comment]
> ** python install.py ** This command is not working on my mobile showing python can't open directory
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. android]
> * Browser [e.g. chrome ]
> * Version [e.g. 105.0.5195.136]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. vivo y91i]
> * OS: [e.g. android 8.1.0]
> * Browser [e.g. chrome]
> * Version [e.g. 105.0.5195.136]
> 
> **Additional context** Add any other context about the problem here.

![IMG_20230207_073611](https://user-images.githubusercontent.com/108191615/217129442-3d4ccdee-4c8f-46a4-adbb-d1226905e1cc.jpg)

Install.py {not added}

**Comment by Desaii01** [comment]
![IMG-20230207-WA0001](https://user-images.githubusercontent.com/124641725/217139719-64bd6f49-eaba-4a3d-9e2a-7131e08e47f2.jpg)

**Comment by Desaii01** [comment]
What to do for this

**Comment by GH05T-HUNTER5** [comment]
> What to do for this

`pkg install python-pip`
