### ISSUE TITLE
Import error in instagram-bruteforcer

### ISSUE THREAD

**Issue by Tanujairamchecked** [GH05T-HUNTER5/GH05T-INSTA#217]
![Screenshot_2023-02-19-10-56-34-609_com termux](https://user-images.githubusercontent.com/94793933/219926231-023d3fc0-9bd5-4ef7-aeb5-90e195e0ecd0.jpg)
**Describe the bug**
Its is not error with my phone or something 

I am sure that this is a error from repo so i didnt prove any information about my device

**Comment by PhilipFobi** [comment]
Same issue here
