### ISSUE TITLE
The script doesn't work

### ISSUE THREAD

**Issue by danielswater** [GH05T-HUNTER5/GH05T-INSTA#242]
Any option I type, it gives an error and then stops the execution

GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors.      
Instagram-Py 2.0.7 ,  Slick Instagram brute force command line tool.                                 
Copyright (C) 2018 The Future Shell , Antony Jr.                                                     
                                                                                                     
[+] Started @ 2023-04-29 10:49:30.054548                                                             
Traceback (most recent call last):                                                                   
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 87, in __init__                                                                                                  
    configuration = json.load(fp)                                                                    
                    ^^^^^^^^^^^^^                                                                    
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load                                     
    return loads(fp.read(),                                                                          
           ^^^^^^^^^^^^^^^^                                                                          
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads                                    
    return _default_decoder.decode(s)                                                                
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode                                    
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode                                
    raise JSONDecodeError("Expecting value", s, err.value) from None                                 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                              
                                                                                                     
During handling of the above exception, another exception occurred:                                  
                                                                                                     
Traceback (most recent call last):                                                                   
  File "/usr/local/bin/instagram-py", line 8, in <module>                                            
    sys.exit(ExecuteInstagramPy())                                                                   
             ^^^^^^^^^^^^^^^^^^^^                                                                    
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/__init__.py", line 128, in ExecuteInstagramPy                                                                                                 
    session = InstagramPySession(                                                                    
              ^^^^^^^^^^^^^^^^^^^                                                                    
  File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 90, in __init__                                                                                                  
    "invalid configuration file at {}".format(configuraion))                                         
                                              ^^^^^^^^^^^^                                           
NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

**Comment by GH05T-HUNTER5** [comment]
> Any option I type, it gives an error and then stops the execution
> 
> GH05T-INSTA 3.01 , gh05t tool helps you to automatically change your IP address and fix errors. Instagram-Py 2.0.7 , Slick Instagram brute force command line tool. Copyright (C) 2018 The Future Shell , Antony Jr.
> 
> [+] Started @ 2023-04-29 10:49:30.054548 Traceback (most recent call last): File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 87, in **init** configuration = json.load(fp) ^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/**init**.py", line 293, in load return loads(fp.read(), ^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/**init**.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/bin/instagram-py", line 8, in sys.exit(ExecuteInstagramPy()) ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/InstagramPy/**init**.py", line 128, in ExecuteInstagramPy session = InstagramPySession( ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/InstagramPy/InstagramPySession.py", line 90, in **init** "invalid configuration file at {}".format(configuraion)) ^^^^^^^^^^^^ NameError: name 'configuraion' is not defined. Did you mean: 'configuration'?

Open new terminal and ran tor

`Then`

Ran this tool
