### ISSUE TITLE
fatal error:: invalid configuration file at /root/instapy-config.json 

### ISSUE THREAD

**Issue by danielswater** [GH05T-HUNTER5/GH05T-INSTA#243]
How does this file have to be configured? I already created it in /root like this:
`{
"username":"my_user",
"password": "my_password"
}`

**Comment by GH05T-HUNTER5** [comment]
> How does this file have to be configured? I already created it in /root like this: `{ "username":"my_user", "password": "my_password" }`

Open new terminal and ran tor

`Then`

Ran this tool

**Comment by danielswater** [comment]
Sorry, but I couldn't understand how I create the file
