### ISSUE TITLE
Não estou conseguindo exucutar

### ISSUE THREAD

**Issue by Adalberto069** [GH05T-HUNTER5/GH05T-INSTA#3]
git clone https://github.com/GH05T-HUNTER5/GH05T-INSTA

**Comment by Adalberto069** [comment]
Esta dando um problema,pede nome do usuario e senha

**Comment by GH05T-HUNTER5** [comment]
> Esta dando um problema,pede nome do usuario e senha

@Adalberto069 Dude try our new update
