### ISSUE TITLE
Linux instalation problem- parrot os

### ISSUE THREAD

**Issue by realspark808** [GH05T-HUNTER5/GH05T-INSTA#38]
File "setup-linux.py", line 34
SyntaxError: Non-ASCII character '\xe2' in file setup-linux.py on line 34, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for deta

**Comment by GH05T-HUNTER5** [comment]
> File "setup-linux.py", line 34 SyntaxError: Non-ASCII character '\xe2' in file setup-linux.py on line 34, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for deta

We are trying to fix this

**Comment by GH05T-HUNTER5** [comment]
> File "setup-linux.py", line 34 SyntaxError: Non-ASCII character '\xe2' in file setup-linux.py on line 34, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for deta

Dude can you share your screenshot
