### ISSUE TITLE
Cant install in linux

### ISSUE THREAD

**Issue by luthfeez7** [GH05T-HUNTER5/GH05T-INSTA#39]
why i cant instal after type python3 setup-linux.py

![Screenshot_2022-12-17_03-18-42](https://user-images.githubusercontent.com/120751614/208182542-7fa6f285-b52c-4c2e-afed-a25ca43617fe.png)
![Screenshot_2022-12-17_03-20-43](https://user-images.githubusercontent.com/120751614/208182626-5ac62c25-3a34-49f0-957f-fa55ad409eac.png)

**Comment by GH05T-HUNTER5** [comment]
> why i cant instal after type python3 setup-linux.py
> 
> ![Screenshot_2022-12-17_03-18-42](https://user-images.githubusercontent.com/120751614/208182542-7fa6f285-b52c-4c2e-afed-a25ca43617fe.png) ![Screenshot_2022-12-17_03-20-43](https://user-images.githubusercontent.com/120751614/208182626-5ac62c25-3a34-49f0-957f-fa55ad409eac.png)

We are trying to resolve the KV package issue within a week

**Comment by GH05T-HUNTER5** [comment]
> why i cant instal after type python3 setup-linux.py
> 
> ![Screenshot_2022-12-17_03-18-42](https://user-images.githubusercontent.com/120751614/208182542-7fa6f285-b52c-4c2e-afed-a25ca43617fe.png) ![Screenshot_2022-12-17_03-20-43](https://user-images.githubusercontent.com/120751614/208182626-5ac62c25-3a34-49f0-957f-fa55ad409eac.png)

Root Must

**Comment by luthfeez7** [comment]
> > why i cant instal after type python3 setup-linux.py
> > ![Screenshot_2022-12-17_03-18-42](https://user-images.githubusercontent.com/120751614/208182542-7fa6f285-b52c-4c2e-afed-a25ca43617fe.png) ![Screenshot_2022-12-17_03-20-43](https://user-images.githubusercontent.com/120751614/208182626-5ac62c25-3a34-49f0-957f-fa55ad409eac.png)
> 
> Please wait

so for now only for termux?

**Comment by GH05T-HUNTER5** [comment]
> > > why i cant instal after type python3 setup-linux.py
> > > ![Screenshot_2022-12-17_03-18-42](https://user-images.githubusercontent.com/120751614/208182542-7fa6f285-b52c-4c2e-afed-a25ca43617fe.png) ![Screenshot_2022-12-17_03-20-43](https://user-images.githubusercontent.com/120751614/208182626-5ac62c25-3a34-49f0-957f-fa55ad409eac.png)
> > 
> > 
> > Please wait
> 
> so for now only for termux?

Try Again 🙂

**Comment by GH05T-HUNTER5** [comment]
> > > why i cant instal after type python3 setup-linux.py
> > > ![Screenshot_2022-12-17_03-18-42](https://user-images.githubusercontent.com/120751614/208182542-7fa6f285-b52c-4c2e-afed-a25ca43617fe.png) ![Screenshot_2022-12-17_03-20-43](https://user-images.githubusercontent.com/120751614/208182626-5ac62c25-3a34-49f0-957f-fa55ad409eac.png)
> > 
> > 
> > Please wait
> 
> so for now only for termux?

Now please reinstall this tool

**Comment by luthfeez7** [comment]
any solution? 
![WhatsApp Image 2022-12-17 at 17 22 42](https://user-images.githubusercontent.com/120751614/208237217-00e117be-cac8-48d5-b05e-44fdc3905725.jpeg)

**Comment by GH05T-HUNTER5** [comment]
> any solution? ![WhatsApp Image 2022-12-17 at 17 22 42](https://user-images.githubusercontent.com/120751614/208237217-00e117be-cac8-48d5-b05e-44fdc3905725.jpeg)

gh05t --error

**Comment by GH05T-HUNTER5** [comment]
> any solution? ![WhatsApp Image 2022-12-17 at 17 22 42](https://user-images.githubusercontent.com/120751614/208237217-00e117be-cac8-48d5-b05e-44fdc3905725.jpeg)

Updated
Now you can install GH05T-INSTA to Linux
