### ISSUE TITLE
about password

### ISSUE THREAD

**Issue by Shadduuu** [GH05T-HUNTER5/GH05T-INSTA#6]
working everythingh of this tool but i don't know which password number should i select out of 20
can u plzz help me out........
and also after getting the paasword where would I will get my password

**Comment by GH05T-HUNTER5** [comment]
> 

Try : 18

**Comment by GH05T-HUNTER5** [comment]
Try 18  :  total password 300000

**Comment by GH05T-HUNTER5** [comment]
> But how much time it will take ?? There are 300000 passwords!

You depend on internet connection

**Comment by Shadduuu** [comment]
Suppose if i try pass no 18  and i am on wifi connection then is it will be uptil 30 mins ??

**Comment by GH05T-HUNTER5** [comment]
> 

Sometimes it takes more than an hour to try all those passwords
