### ISSUE TITLE
tell me how to use ./gh05t in terminal 

### ISSUE THREAD

**Issue by thedarksoul02** [GH05T-HUNTER5/GH05T-INSTA#60]
what to write before ./gh05t 
its to a correct commond

**Comment by GH05T-HUNTER5** [comment]
> what to write before ./gh05t its to a correct commond

./setup-linux.sh

./gh05t --help

**Comment by GH05T-HUNTER5** [comment]
> what to write before ./gh05t its to a correct commond

`Install Home` 

`$ cd home/`
