### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by Ahmedmi96** [GH05T-HUNTER5/GH05T-INSTA#61]
![SmartSelect_20230124-012516_Termux](https://user-images.githubusercontent.com/123424892/214175669-fd19f0a9-87cf-4dbd-b144-1deeaab1cbcc.jpg)
I'm using termux with non rooted phone 
Please help 
I think this last step and it'll works
Thanks

**Comment by GH05T-HUNTER5** [comment]
> ![SmartSelect_20230124-012516_Termux](https://user-images.githubusercontent.com/123424892/214175669-fd19f0a9-87cf-4dbd-b144-1deeaab1cbcc.jpg) I'm using termux with non rooted phone Please help I think this last step and it'll works Thanks

$ gh05t uninstall all

Reinstall

**Comment by smallLTN** [comment]
having the same problem after uninstall and reinstall

**Comment by GH05T-HUNTER5** [comment]
> having the same problem after uninstall and reinstall

$ `gh05t --check`

$ `gh05t --error`

$ `apt upgrade`

$ `pkg install tor`

$ `apt update tor -y`

$ `gh05t --update`

**Comment by spyro-ser-ofc** [comment]
> 

![IMG-20230126-WA0284](https://user-images.githubusercontent.com/92428473/214776404-f49a4240-53ae-4a36-965c-ee96cb9422e1.jpg)

**Comment by GH05T-HUNTER5** [comment]
> > 
> 
> ![IMG-20230126-WA0284](https://user-images.githubusercontent.com/92428473/214776404-f49a4240-53ae-4a36-965c-ee96cb9422e1.jpg)

Not ready bro
