### ISSUE TITLE
How do we see the password 

### ISSUE THREAD

**Issue by smallLTN** [GH05T-HUNTER5/GH05T-INSTA#62]
Where does the password show up after the test. 
(i have not got it because of this bug)

<img width="287" alt="Screen Shot 2023-01-24 at 12 35 07 AM" src="https://user-images.githubusercontent.com/123439847/214219519-bea6426e-866f-42a9-8850-e8ab340020cc.png">

**Comment by GH05T-HUNTER5** [comment]
> Where does the password show up after the test. (i have not got it because of this bug)
> 
> <img alt="Screen Shot 2023-01-24 at 12 35 07 AM" width="287" src="https://user-images.githubusercontent.com/123439847/214219519-bea6426e-866f-42a9-8850-e8ab340020cc.png">

We are trying to solve this problem
