### ISSUE TITLE
Slove the problem 

### ISSUE THREAD

**Issue by spyro-ser-ofc** [GH05T-HUNTER5/GH05T-INSTA#90]
![IMG-20230126-WA0284](https://user-images.githubusercontent.com/92428473/214776719-02dbbe37-c523-4a7d-8013-eee7120a440c.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GH05T-HUNTER5** [comment]
> ![IMG-20230126-WA0284](https://user-images.githubusercontent.com/92428473/214776719-02dbbe37-c523-4a7d-8013-eee7120a440c.jpg) **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Not ready bro
